### ISSUE TITLE
Editor (input field) loosing focus

### ISSUE THREAD

**Issue by Sandeep-Tech** [Doist/typist#44] opened 2022-12-05 07:28 UTC
Context: I have embedded 'typist' in my app which is a extension that attaches to Whatsapp Web.
The typist editor looses focus to whatsapp's chat editor as shown in the video below:

[screen-capture-1.webm](https://user-images.githubusercontent.com/23122564/205579780-ec837ee5-b1b2-483b-8214-6e0722e83cbb.webm)

The problem doesn't show up in [isolated case](https://stackblitz.com/edit/souk-doist-typist-demo?file=src%2FApp.js,src%2FEditor.js) Here is the snippet I am using in my project:

```react.js
RichTextKit.configure({
  document: {
    multiline: false,
  },
});

function RichTextInput({ content, onUpdate }) {
  const typistEditorRef = useRef(null);

  const handleUpdate = useEvent(({ getMarkdown }) => {
    onUpdate(getMarkdown());
    typistEditorRef.focus();
  });

  return (
    <TypistEditor
      className="rich-text-input"
      content={content}
      extensions={[RichTextKit]}
      onUpdate={handleUpdate}
      ref={typistEditorRef}
    />
  );
}
```

```react.js
<RichTextInput
  content={richTextInputContent}
  onUpdate={setRichTextInputContent}
/>
```

Here is a clip showing the behaviour with `autoFocus` prop
[screen-capture-autoFocus.webm](https://user-images.githubusercontent.com/23122564/205580910-72b47a6a-eb26-4c68-b56c-268e4f2a7207.webm)

**Comment by henningmu** [comment] 2022-12-05 13:24
@Sandeep-Tech without an example to reproduce, this is hard for us to debug / understand. If you could provide one that would greatly help us, help you.

Meanwhile, the `handleUpdate` function seems to be calling `typistEditorRef.focus()` which is not possible. Please try using `typistEditorRef.current.getEditor().commands.focus()` instead. Documentation on [`commands` can be found here](https://tiptap.dev/api/commands/focus).

I'm closing this, assuming the above will work for you. If it doesn't, please feel free to reopen 👍

**Closed by henningmu** 2022-12-05 13:24 UTC
